import { LegalPageShell, LEGAL_CONTACT_PRIVACY, LEGAL_CONTACT_AP, LEGAL_EFFECTIVE, LEGAL_ENTITY, LEGAL_PLATFORM } from "./LegalPageShell";

/**
 * Public Privacy Policy for the Emerald CFZE SCM Platform.
 * Drafted for operational use; have counsel review before relying on it as final legal advice.
 */
export default function PrivacyPolicyPage() {
  return (
    <LegalPageShell
      title="Privacy Policy"
      effectiveDate={LEGAL_EFFECTIVE}
      lastUpdated={LEGAL_EFFECTIVE}
    >
      <section className="space-y-3">
        <h2>1. Who we are</h2>
        <p>
          This Privacy Policy explains how <strong className="text-foreground">{LEGAL_ENTITY}</strong>{" "}
          (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;) collects, uses, stores, and shares
          personal and business information when you use the {LEGAL_PLATFORM} (the &quot;Platform&quot;),
          including the staff SCM portals, Vendor Portal, material and service requisitions, RFQs,
          purchase orders, logistics, warehouse, and related finance workflows.
        </p>
        <p>
          For privacy questions, contact us at{" "}
          <a href={`mailto:${LEGAL_CONTACT_PRIVACY}`}>{LEGAL_CONTACT_PRIVACY}</a>. For accounts-payable
          related queries, you may also reach{" "}
          <a href={`mailto:${LEGAL_CONTACT_AP}`}>{LEGAL_CONTACT_AP}</a>.
        </p>
      </section>

      <section className="space-y-3">
        <h2>2. Scope</h2>
        <p>This Policy applies to:</p>
        <ul>
          <li>Employees, contractors, and authorised internal users of {LEGAL_ENTITY}</li>
          <li>Vendors, suppliers, and their authorised representatives using the Vendor Portal</li>
          <li>Applicants submitting vendor registration or related onboarding information</li>
          <li>Individuals whose details appear in requisitions, trip requests, delivery records, or similar Platform records</li>
        </ul>
        <p>
          This Policy is intended to align with applicable Nigerian data-protection expectations,
          including the Nigeria Data Protection Act, 2023 (NDPA) and related regulations, where they apply.
        </p>
      </section>

      <section className="space-y-3">
        <h2>3. Information we collect</h2>
        <h3>3.1 Account and identity data</h3>
        <ul>
          <li>Name, email address, phone number, department, and role</li>
          <li>Login credentials and authentication tokens</li>
          <li>Vendor company name, registration/tax identifiers, contact persons, and addresses</li>
        </ul>
        <h3>3.2 Procurement and operational data</h3>
        <ul>
          <li>Material Request Forms (MRFs), Service Request Forms (SRFs), RFQs, quotations, and purchase orders</li>
          <li>Approvals, rejections, remarks, workflow history, and supporting documents</li>
          <li>Logistics and trip details, driver/fleet information used for business operations</li>
          <li>Warehouse inventory, delivery confirmation, GRN, and related fulfilment records</li>
        </ul>
        <h3>3.3 Financial and banking data (vendors)</h3>
        <ul>
          <li>Bank name, account name, and account number provided for payment processing</li>
          <li>Payment schedules, invoices, and accounts-payable references where processed through the Platform</li>
        </ul>
        <h3>3.4 Technical and usage data</h3>
        <ul>
          <li>Device/browser type, IP address, timestamps, and security/audit logs</li>
          <li>Session and preference data (for example theme or “keep me signed in” settings stored locally)</li>
        </ul>
        <p>
          We collect information you submit directly, information created through Platform workflows
          (for example approvals by colleagues), and limited technical data generated by your use of the service.
        </p>
      </section>

      <section className="space-y-3">
        <h2>4. How we use information</h2>
        <p>We use information to:</p>
        <ul>
          <li>Operate procurement, vendor management, logistics, warehouse, and finance workflows</li>
          <li>Authenticate users, enforce role-based access, and maintain audit trails</li>
          <li>Evaluate vendor applications, issue RFQs, receive quotations, and generate purchase orders</li>
          <li>Coordinate deliveries, inventory, and related operational follow-up</li>
          <li>Process or facilitate payments and supplier communications</li>
          <li>Send service notifications (approvals, RFQs, status changes, password resets)</li>
          <li>Improve security, prevent fraud/abuse, and meet legal or regulatory obligations</li>
          <li>Produce internal management reporting and operational analytics</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2>5. Legal bases</h2>
        <p>Where required by law, we process personal data on bases that may include:</p>
        <ul>
          <li>Performance of a contract or steps prior to entering a contract (for example vendor onboarding or fulfilling a PO)</li>
          <li>Legitimate interests in running secure, auditable supply-chain operations</li>
          <li>Compliance with legal obligations</li>
          <li>Consent, where we expressly ask for it (for example certain optional communications)</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2>6. Sharing and disclosure</h2>
        <p>We may share information with:</p>
        <ul>
          <li>
            <strong className="text-foreground">Internal teams</strong> (procurement, supply chain, executive,
            finance, logistics, warehouse) on a need-to-know basis according to role permissions
          </li>
          <li>
            <strong className="text-foreground">Vendors and counterparties</strong> as needed to run RFQs,
            POs, deliveries, and related communications
          </li>
          <li>
            <strong className="text-foreground">Service providers</strong> who host, store, email, or
            otherwise support the Platform under confidentiality and security obligations
          </li>
          <li>
            <strong className="text-foreground">Professional advisers, auditors, or authorities</strong>{" "}
            where required by law, regulation, or to protect our rights and safety
          </li>
        </ul>
        <p>We do not sell personal information.</p>
      </section>

      <section className="space-y-3">
        <h2>7. International transfers and hosting</h2>
        <p>
          The Platform and related backups or infrastructure may be hosted on cloud services that
          process data in or outside Nigeria. Where data is transferred internationally, we take
          reasonable steps consistent with applicable law to protect it.
        </p>
      </section>

      <section className="space-y-3">
        <h2>8. Retention</h2>
        <p>
          We retain account, procurement, vendor, logistics, warehouse, and finance records for as
          long as needed for operational, audit, contractual, tax, and legal purposes. When data is
          no longer required, we delete or anonymise it where practicable, subject to backup and
          legal hold constraints.
        </p>
      </section>

      <section className="space-y-3">
        <h2>9. Security</h2>
        <p>
          We use administrative, technical, and organisational measures appropriate to the nature of
          the Platform, including authentication, role-based access control, encrypted transport
          (HTTPS), and audit logging. No system is perfectly secure; please keep credentials confidential
          and notify us promptly of any suspected unauthorised access.
        </p>
      </section>

      <section className="space-y-3">
        <h2>10. Your rights</h2>
        <p>
          Subject to applicable Nigerian law, you may have rights to request access, correction,
          deletion, restriction, or objection to certain processing, and to lodge a complaint with
          the relevant data-protection authority. To exercise rights, contact{" "}
          <a href={`mailto:${LEGAL_CONTACT_PRIVACY}`}>{LEGAL_CONTACT_PRIVACY}</a>. We may need to
          verify your identity and may refuse requests where an exemption applies (for example
          retention required for audits or legal claims).
        </p>
      </section>

      <section className="space-y-3">
        <h2>11. Cookies and local storage</h2>
        <p>
          The Platform may use cookies or browser local storage for authentication sessions,
          preferences (such as theme), and similar essential functions. Disabling these may prevent
          sign-in or degrade functionality.
        </p>
      </section>

      <section className="space-y-3">
        <h2>12. Children</h2>
        <p>
          The Platform is a business system and is not directed at children. We do not knowingly
          collect personal data from children for Platform use.
        </p>
      </section>

      <section className="space-y-3">
        <h2>13. Changes</h2>
        <p>
          We may update this Privacy Policy from time to time. The &quot;Last updated&quot; date at
          the top will change when we do. Continued use of the Platform after changes take effect
          constitutes acceptance of the updated Policy, except where applicable law requires
          additional notice or consent.
        </p>
      </section>

      <section className="space-y-3">
        <h2>14. Contact</h2>
        <p>
          <strong className="text-foreground">{LEGAL_ENTITY}</strong>
          <br />
          Privacy / procurement:{" "}
          <a href={`mailto:${LEGAL_CONTACT_PRIVACY}`}>{LEGAL_CONTACT_PRIVACY}</a>
          <br />
          Accounts payable:{" "}
          <a href={`mailto:${LEGAL_CONTACT_AP}`}>{LEGAL_CONTACT_AP}</a>
        </p>
      </section>
    </LegalPageShell>
  );
}
