/**
 * PO-related helpers: defensive accessors for backend payload shape variance.
 * Backend may return either camelCase / snake_case AND singular / plural keys
 * depending on serializer version. Always go through these helpers.
 */

export interface PriceComparisonRow {
  vendorName: string;
  itemDescription: string;
  unitPrice: number;
  quantity: number;
  totalPrice: number;
  selected: boolean;
  selectionReason?: string;
}

const num = (v: unknown): number => {
  if (v == null) return 0;
  const n = typeof v === "number" ? v : parseFloat(String(v));
  return Number.isFinite(n) ? n : 0;
};

/**
 * Resolve the price-comparison rows attached to a PO regardless of
 * which key the backend chose (priceComparison / priceComparisons /
 * price_comparison / price_comparisons).
 */
export const getPriceComparison = (po: any): PriceComparisonRow[] => {
  if (!po) return [];

  const rawCandidates = [
    po.priceComparison,
    po.priceComparisons,
    po.price_comparison,
    po.price_comparisons,
  ].filter((v) => Array.isArray(v));

  // Dev warning if multiple non-empty variants disagree
  if (
    typeof window !== "undefined" &&
    import.meta.env?.DEV &&
    rawCandidates.length > 1
  ) {
    const lengths = new Set(rawCandidates.map((a) => a.length));
    if (lengths.size > 1) {
      // eslint-disable-next-line no-console
      console.warn(
        "[poHelpers] PO returned multiple price-comparison keys with different lengths",
      );
    }
  }

  const raw: any[] = rawCandidates[0] ?? [];

  return raw.map((r) => {
    const unitPrice = num(r.unitPrice ?? r.unit_price);
    const quantity = num(r.quantity ?? r.qty);
    const totalPrice = num(
      r.totalPrice ?? r.total_price ?? unitPrice * quantity,
    );
    return {
      vendorName:
        r.vendorName ?? r.vendor_name ?? r.vendor?.name ?? "Unknown vendor",
      itemDescription:
        r.itemDescription ??
        r.item_description ??
        r.description ??
        r.item ??
        "",
      unitPrice,
      quantity,
      totalPrice,
      selected: Boolean(r.selected ?? r.is_selected ?? r.isSelected),
      selectionReason:
        r.selectionReason ?? r.selection_reason ?? r.reason ?? undefined,
    };
  });
};

/** Normalized PO status string (lowercased, snake-cased). */
export const getPOStatus = (po: any): string => {
  if (!po) return "";
  const raw = String(po.status ?? po.po_status ?? "").trim();
  return raw.toLowerCase().replace(/[\s-]+/g, "_");
};

/** True if the PO has been returned to procurement for revision. */
export const isPORevisionRequired = (po: any): boolean => {
  const s = getPOStatus(po);
  return s === "revision_required" || s === "returned_to_procurement";
};

/** True if the PO is awaiting SCD signature. */
export const isPOAwaitingSignature = (po: any): boolean =>
  getPOStatus(po) === "awaiting_scd_signature";

/** Pull a rejection reason from any of the common backend keys. */
export const getRejectionReason = (po: any): string | undefined => {
  if (!po) return undefined;
  return (
    po.rejectionReason ??
    po.rejection_reason ??
    po.poRejectionReason ??
    po.po_rejection_reason ??
    undefined
  );
};

/** Resolve the effective PO identifier exposed by the backend payload. */
export const getEffectivePoNumber = (mrf: any): string | undefined => {
  if (!mrf) return undefined;

  const candidates = [
    mrf.poNumber,
    mrf.po_number,
    mrf.effectivePoNumber,
    mrf.effective_po_number,
    mrf.linked_po_id,
    mrf.linkedPoId,
  ];

  for (const candidate of candidates) {
    if (candidate == null) continue;
    const value = String(candidate).trim();
    if (value) return value;
  }

  return undefined;
};

/** True when the MRF has a usable PO identity for edit / action entry points. */
export const hasEffectivePoIdentity = (mrf: any): boolean => {
  if (!mrf) return false;

  const poNumber = getEffectivePoNumber(mrf);
  if (poNumber) return true;

  const linkedId = String(
    mrf.linked_po_id ?? mrf.linkedPoId ?? "",
  ).trim();
  const isLinked = mrf.is_po_linked === true || mrf.isPoLinked === true;
  return Boolean(isLinked && linkedId);
};

/**
 * Item 2 — True when an MRF was generated by the manual PO creation flow.
 *
 * Backend should ultimately set `source: 'po_generated'` and/or `is_po_linked: true`
 * on the MRF record. Until that ships, we fall back to a heuristic: any MRF that
 * carries a linked PO id AND whose creation path looks like manual-PO.
 *
 * PO-generated MRFs MUST be filtered out of: Active MRFs, Official MRFs, All MRFs.
 * They remain visible inside Procurement History and inside the PO record itself.
 *
 * Swap-to-flag: once the backend always returns one of `source`/`is_po_linked`,
 * the heuristic branches at the bottom can be removed.
 */
export const isPoGeneratedMrf = (mrf: any): boolean => {
  if (!mrf) return false;

  // Authoritative flags (preferred, once backend ships them).
  const source = String(mrf.source ?? mrf.mrf_source ?? '').toLowerCase();
  if (source === 'po_generated' || source === 'manual_po') return true;
  if (mrf.is_po_linked === true || mrf.isPoLinked === true) return true;
  if (mrf.suppress_notifications === true || mrf.suppressNotifications === true) return true;

  // Heuristic fallbacks — ALL must be evaluated independently. Earlier versions
  // gated the justification-text branch behind `hasLinkedPo`, which silently
  // failed for half-finished manual POs that never produced a PO row.
  const createdVia = String(
    mrf.created_via ?? mrf.createdVia ?? mrf.creation_method ?? mrf.creationMethod ?? '',
  ).toLowerCase();
  if (
    createdVia === 'manual_po' ||
    createdVia === 'po' ||
    createdVia === 'po_generated'
  ) {
    return true;
  }

  const hasLinkedPo = Boolean(
    mrf.linked_po_id ?? mrf.linkedPoId ?? mrf.manual_po_id ?? mrf.manualPoId,
  );
  if (hasLinkedPo) return true;

  // Justification text written by ManualPOQuickStartDialog (the only persistent
  // signal until backend stores `source`/`is_po_linked`).
  const just = String(mrf.justification ?? '').toLowerCase();
  if (
    just.includes('manual po created without rfq') ||
    just.includes('vendor and pricing captured directly on the purchase order')
  ) {
    return true;
  }

  // ───────────────────────────────────────────────────────────────────────────
  // TEMPORARY fallback (remove once backend reliably persists
  // `source` / `is_po_linked` / `linked_po_id` on MRF create + list payloads):
  //
  // Some backend code paths drop the justification text and the explicit flags
  // on the floor when the MRF is created as a side-effect of a manual PO. As a
  // last-resort heuristic, treat any MRF whose title/description/notes carries
  // an auto-generated PO reference (e.g. "PO-EMERALD-2026-049",
  // "PO-PRC-OFFI-2026-049", "po_number: PO-...") as PO-generated and hide it
  // from standard list surfaces.
  // ───────────────────────────────────────────────────────────────────────────
  const poRefRegex = /\bPO-[A-Z0-9]+(?:-[A-Z0-9]+){1,}\b/i;
  const haystack = [
    mrf.title,
    mrf.description,
    mrf.notes,
    mrf.summary,
    mrf.po_number,
    mrf.poNumber,
  ]
    .map((v) => (v == null ? '' : String(v)))
    .join(' ');
  if (poRefRegex.test(haystack)) return true;

  return false;
};

/** Filter helper for list surfaces. Keeps non-PO MRFs only. */
export const excludePoGeneratedMrfs = <T,>(items: T[] | null | undefined): T[] => {
  if (!Array.isArray(items)) return [];
  return items.filter((m) => !isPoGeneratedMrf(m));
};